### PR TITLE
Some janitoring

### PR DESCRIPTION
**Pull request by picobyte**
These patches are also split out from the original pull request -before any of the skippy ball changes. Let me know if you disagree with any of the changes, in particular in Bladder.i7x in patch
 `split out janitoring changes.`
The code as it was seemed wrong, but maybe you'd like it fixed differently.

Also two behavioural changes in:
`When too light pressure traps won't trigger`
and
`only keep logic that if part of something a dildo cannot be spawned or fall out`
But this seems sensible to me and the last patch allows some use cases of a dildo part of something

### CODE REVIEW

**Comment by aika092** [comment]
Thanks a lot for this.  The bladder code has some weird edge cases.  Imagine the bladder of the player is 16 and then we BladderUp 1.  We would add 2, making the bladder of the player 18, but then we would subtract 4, meaning the new bladder of the player is 14 - less than what it started at.  I will make a change to it so that this doesn't happen.

**Comment by picobyte** [comment]
You're welcome & thanks for the Christmas release. I've made some progress
with the skippy ball requested changes (skippyball*2* branch), also see
google doc I shared, editable, with you, if you didn't see it, you could
use the link below.

https://docs.google.com/document/d/1XdKS3NS9O9viDAhEsHWbg9hZiQqxn99Mb2eCi_gXQuM/edit?usp=sharing

The stance changes touch many files. I tried to make this stance
'extendable'. Maybe you want to implement a tricycle later (I'm not into
something like that though). Or maybe/possibly riding a pony or unicorn?
(not a bronie either though.)

Also if you'd like to have more lingerie, I may have some, e.g these three:

**Comment by picobyte** [comment]
or a cat image

**Comment by aika092** [comment]
Hi PicoByte, if you meant to upload images I'm having trouble seeing them.  The skippy ball looks like we can get it to a place where it's functional, which is great.  However things like this which add so much complexity to the game are definitely things I want to shy away from in the long term because it adds too much to think about.  It's the same reason I regret implementing the latex curse - it means that every single player-activated action, every single automatic action, every single NPC, every single trap and so on from now on must ask the question 'what happens differently if the player is in this unique state'?  And if there are too many of those then adding new stuff becomes an utter nightmare.  The way the game has gotten so big so far without grinding to a complete halt is because the number of possible player states have remained rather static even though the game content has increased so much.  `Immobile` covers most things, and if the player isn't immobile then they're probably available for sex, traps, dragging and so on.  There's only a few other things to consider, generally - clothing that might be in the way of things, what body parts are available, whether the player is the living sex doll, and that's usually pretty much it.

So we'll add the skippy ball once it's been tested enough but after this we should definitely try to avoid things that add such brand new unique states to the player!

**Pull request merged**
